### ISSUE TITLE
"Archive" label becomes global

### ISSUE THREAD

**Issue by panoysia** [raihan2006i/active_admin_paranoia#10]
Hi,

Is there a way to prevent the gem from using the label "Archive" for resources that didn't declare active_admin_paranoia in them?

I've got only one resource that used the gem but the "Archive" label overrides all labels of my other resources.

How can I prevent it? In the locale/en.yml?

Thank you.

**Comment by raihan2006i** [comment]
@panoysia Not sure if we can mark this issue as bug or not, because yes you have to prevent it in https://github.com/raihan2006i/active_admin_paranoia/blob/master/config/locales/en.yml

**Comment by panoysia** [comment]
So I simply re-declare/overwrite it in my app's locale.en.yml?

Is there a way to do it per-specific resource? I've only one resource that needs the "Archive" and the rest doesn't. Any idea how to do it in the locale.en.yml?

**Comment by raihan2006i** [comment]
@panoysia Yes you have to re-declare in you apps locale en.yml file. No there is no way to do it per-specific resource at the moment. I have to investigate if I can achieve with activeadmin dsl. I will check in my free time

**Comment by panoysia** [comment]
No problem @raihan2006i. For now, I'll have to do it manually without the gem.

Thank you!

**Comment by artemv** [comment]
@panoysia just in case - I've fixed it in my fork, https://github.com/artemv/active_admin_paranoia

**Comment by panoysia** [comment]
Thanks for the heads up @artemv! I'll try to play with it.

**Comment by raihan2006i** [comment]
@artemv  can you please create a pull request? I will have a look and then i will merge after testing :+1:

**Comment by raihan2006i** [comment]
@artemv anyway I found that you already created the pull requested :+1: Soon i will merge. Thanks again for the pull request
