### ISSUE TITLE
I will be maintaining a fork: https://github.com/DocSpring/active_admin_paranoia

### ISSUE THREAD

**Issue by ndbroadbent** [raihan2006i/active_admin_paranoia#18]
I've been using activeadmin and paranoia for a long time and I just discovered this active_admin_paranoia gem. 

I've cherry-picking all of the open PRs into my fork: https://github.com/DocSpring/active_admin_paranoia
I have a test suite with a high level of test coverage (including all my admin pages and features), so I will be maintaining my fork and fixing any issues when Rails or activeadmin is updated. Please feel free to use my fork:

```
gem 'active_admin_paranoia', github: 'DocSpring/active_admin_paranoia', branch: :master
```

---

@raihan2006i I'd also be happy to help maintain this repo and merge PRs / push new versions to Rubygems if you would like some help. Thanks for the gem!

**Comment by raihan2006i** [comment]
@ndbroadbent Thanks for contacting me and contributing. I am happy to add you as a maintainer for this gem in GitHub and owner in RubyGems. Could you please give me your RubyGems username?

**Comment by raihan2006i** [comment]
@ndbroadbent I already invited you as a collaborator for this repo in GitHub; please accept

**Comment by ndbroadbent** [comment]
Awesome, thanks! My rubygems username is ndbroadbent

**Comment by raihan2006i** [comment]
@ndbroadbent Added you as another owner to https://rubygems.org/gems/active_admin_paranoia
Let me know whether you have the access

**Comment by ndbroadbent** [comment]
@raihan2006i Thanks I have access to the GitHub repo, but I don't have access to https://rubygems.org/gems/active_admin_paranoia yet. I don't see anything in my rubygems account and didn't receive any emails. Could you please try again? Thanks!

**Comment by raihan2006i** [comment]
@ndbroadbent You should receive an invitation now from https://rubygems.org/gems/active_admin_paranoia

**Comment by ndbroadbent** [comment]
Got it, thanks!
