### ISSUE TITLE
Restore Batch action raises an error

### ISSUE THREAD

**Issue by vraravam** [raihan2006i/active_admin_paranoia#2]
With the latest version of the gem, the restore batch action raises an error.

AbstractController::ActionNotFound - AbstractController::ActionNotFound:
() bundler/gems/activeadmin-5a2b7b5bc683/lib/active_admin/base_controller.rb:29:in `only_render_implemented_actions'
activesupport (4.2.3) lib/active_support/callbacks.rb:430:in`block in make_lambda'

**Comment by raihan2006i** [comment]
@vraravam Can I close this issue? Did you fix it in pull request https://github.com/raihan2006i/active_admin_paranoia/pull/3?

**Comment by vraravam** [comment]
Yes - this issue is fixed as part of the lined PR
